@host = http://localhost:8009

POST {{host}}/predict 
Content-Type: application/json

{
    "n_days": 10
    // ,"prices": [50,52,49.1,51,53,48,50.5,49.8,52.2,51.5]
}

###

GET {{host}}/metrics


###

GET {{host}}/health